### ISSUE TITLE
Readme needs to be improved. (+A few questions)

### ISSUE THREAD

**Issue by TheLastMillennial** [Skyluker4/NES84#1]
I recently found this project and I'm quite interested in seeing how it develops. However, the ReadMe is not very informative on what works and how to use it. I would appreciate it if you could add what this program currently does since it just sits on the home screen for me and does nothing.

Unrelated: If you're interested, it'd be neat if you would share your progress and goals for this project on a calculator forum such as [Cemetech.net](https://www.cemetech.net/). 
How are you planning to achieve decent emulation speeds?

**Comment by Skyluker4** [comment]
I just updated the readme and posted more information on the [forum](https://www.cemetech.net/forum/viewtopic.php?p=275975#275975).

Right now the program does nothing, all that's done is the CPU, and it doesn't execute anything. I'm currently working on testing it now, so I should have ROMs be able to load soon, but it still won't display anything until the PPU is done. For now, it's just going to have to sit on a blank screen for a while until that's done.
